site_name: Web Docs

nav:
  - Home: index.md
  - Labs:
      - Лабораторная работа №1:
          - "Задание 1": lab1/task_1.md
          - "Задание 2": lab1/task_2.md
          - "Задание 3": lab1/task_3.md
          - "Задание 4": lab1/task_4.md
          - "Задание 5": lab1/task_5.md
      - Лабораторная работа №2:
          - Задание: lab2/index.md
          - Модели: lab2/models.md
          - Представления: lab2/view.md
          - Формы: lab2/forms.md
          - Итоговый результат: lab2/result.md
