site_name: Web Docs

nav:
  - Home: index.md
  - Labs:
      - Лабораторная работа №1:
          - "Задание 1": lab1/task_1.md
          - "Задание 2": lab1/task_2.md
          - "Задание 3": lab1/task_3.md
          - "Задание 4": lab1/task_4.md
          - "Задание 5": lab1/task_5.md

      - Лабораторная работа №2:
          - Задание: lab2/index.md
          - Модели: lab2/models.md
          - Представления: lab2/view.md
          - Формы: lab2/forms.md
          - Итоговый результат: lab2/result.md

      - Лабораторная работа №3:
            - Models: lab3/models.md
            - Endpoints:
                  - Client: lab3/client.md
                  - Employee_contracts: lab3/employee_contracts.md
                  - Agents: lab3/agents.md
                  - Specializations: lab3/specializations.md
                  - Payouts: lab3/payouts.md
                  - Enterprises: lab3/enterprises.md
                  - Contracts: lab3/contracts.md
                  - Claims: lab3/claims.md
